name: Deploy to Ubuntu

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Ubuntu
      run: |
        ssh -o StrictHostKeyChecking=no bryanpp@172.19.254.185 "cd /home/bryanpp/GITHUB/airflow_cobrit && git pull && docker-compose up -d"
